### ISSUE TITLE
[Bug]: With WLED v0.13.2 plugin causes random LED flashing

### ISSUE THREAD

**Issue by ShuffleBit** [cp2004/OctoPrint-WLED#223] opened 2022-07-13 13:39 UTC
EDIT: Close this. This is AirCookie's WLED bug. Defining a black segment causes flashing in WLED 0.13.1 and 0.13.2-a0. The tell: the flashing is visible in WLED's web ui using "Peek" **after** removing the plugin.

### Description of the bug

First, this is brilliant. I started to code my own when it occurred to me to look for this specifically.

What I'm observing: A 131 LED WS2812b strip on an ESP8266 d1 mini running WLED 0.13.2 randomly flashes the print progress segment (0-40) when printing starts. 

This flashing also appears in WLED's web interface "Peek" function, so WLED is being told to flash the segment (ie, it's not noise, not level mismatch, not underpowered).

On the plus side, this makes OctoLapse videos look Olde-Timey.

### Software versions

OctoPrint 1.8.1, WLED Connection 0.2.1, WLED 0.13.2-a0

### Logs and screenshots

[octoprint-systeminfo-20220713133721.zip](https://github.com/cp2004/OctoPrint-WLED/files/9102694/octoprint-systeminfo-20220713133721.zip)

**Comment by cp2004** [comment] 2022-07-14 14:16
> EDIT: Close this. This is AirCookie's WLED bug. Defining a black segment causes flashing in WLED 0.13.1 and 0.13.2-a0. The tell: the flashing is visible in WLED's web ui using "Peek" after removing the plugin.

Ah, I was just thinking about what could be the cause of this problem from the plugin's side, then I saw the edit. I'll close this issue then.

If you need any further help, please ask.

**Closed by cp2004** 2022-07-14 14:16 UTC
